// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mongodb.proto

#include "mongodb.pb.h"
#include "mongodb.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mongodb {

static const char* Transport_method_names[] = {
  "/mongodb.Transport/SendMessage",
};

std::unique_ptr< Transport::Stub> Transport::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Transport::Stub> stub(new Transport::Stub(channel));
  return stub;
}

Transport::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendMessage_(Transport_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Transport::Stub::SendMessage(::grpc::ClientContext* context, const ::mongodb::Message& request, ::mongodb::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mongodb::Message, ::mongodb::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void Transport::Stub::experimental_async::SendMessage(::grpc::ClientContext* context, const ::mongodb::Message* request, ::mongodb::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mongodb::Message, ::mongodb::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void Transport::Stub::experimental_async::SendMessage(::grpc::ClientContext* context, const ::mongodb::Message* request, ::mongodb::Message* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mongodb::Message>* Transport::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::mongodb::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mongodb::Message, ::mongodb::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mongodb::Message>* Transport::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::mongodb::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

Transport::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Transport_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Transport::Service, ::mongodb::Message, ::mongodb::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Transport::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mongodb::Message* req,
             ::mongodb::Message* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
}

Transport::Service::~Service() {
}

::grpc::Status Transport::Service::SendMessage(::grpc::ServerContext* context, const ::mongodb::Message* request, ::mongodb::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mongodb

